import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false

export const metadata: Metadata = {
  title: "book-search",
  description: "Generated by create next app",
};
 
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header>
          <a href="/">ログイン</a>
        </header>
        {children}
      </body>
    </html>
  );
}
